Add blocks and dynamic schedule page
HackGT/live-site-old pull request #14
Opened 2018-02-25 21:24 UTC by evan10s

Fancy things!  See the details below:

- Updated generic pages to be a one-column layout
- Added dynamic schedule page (generated using the Google Calendar API)
- Added "blocks" - reusable sections of information that can be included in special one and two column layouts
- Made the home.md file in /event_page appear when you go to /

2018-02-26 03:42 UTC, evan10s commented
Closes #5, #9, #10, #11, #14

2018-02-28 22:57 UTC, mjkaufer requested changes
I'm not a good person to get feedback for the Jekyll but w.r.t. to the JS, looks pretty good, small requests here, big request at the end:

* Get rid of console logs
* Add a comment around the anonymous function so ppl in the future editing this don't get shook

I'm pretty sure there's a really big XSS vulnerability via the calendar (i.e. event title called `<script>alert('lmao')</script>`). On one hand, that shouldn't be an issue because we control the calendar, but on the other I feel like we shouldn't have it as a potential issue regardless. I think you can escape the string, or since you're using jQuery, you can add your table elements to the DOM and then set their text. Also maybe google calendar already escapes stuff, but I'm not sure, and would rather not risk it.

Also, you included an API key in your `schedule.md` which implies we'd need to put it there consistently in the future, and biodomes mandates our repos are public. Would there be any way to make it an environment variable instead?

Otherwise, dope work!

2018-02-28 23:11 UTC, evan10s commented
With the calendar API key, that's exposed to the client.  So I thought it's fine to keep in the repo.  We can restrict the key so it only works for certain http referers, like only subdomains of *.hack.gt

The other stuff should all be fixed, so I'll take a look at those items

2018-03-01 04:32 UTC, evan10s commented
To do list of things to fix:

- [ ] Remove all `console.log` statements in the JS
- [ ] Add a comment about the anonymous function in `schedule.js`
- [ ] Use jQuery's `.text()` method to safely add calendar events to the DOM
- [ ] Add methods to gracefully catch failed AJAX requests and retry automatically

2018-03-02 04:50 UTC, illegalprime requested changes
:mag:

2018-03-02 04:50 UTC, illegalprime commented on _includes/head.html
> +    <script src="/assets/jquery-3.3.1.min.js"></script>
Please remove this.

2018-03-02 04:50 UTC, illegalprime commented on _includes/head.html
> +    <script src="/assets/jquery-3.3.1.min.js"></script>
also optionally es6?

2018-03-02 04:56 UTC, evan10s commented on _includes/head.html
> +    <script src="/assets/jquery-3.3.1.min.js"></script>
The schedule uses jQuery to render itself for simplicity, but I can move the JS stuff to the footer to reduce the impact on pageload times.

We could do es6, but I'm pretty sure there are still devices with browsers that still don't support it, and adding a transpiler like Babel seems too complex for the minimal benefit (it's not like we need `async await` for any of this).

2018-03-02 04:58 UTC, mjkaufer requested changes

2018-03-02 04:58 UTC, mjkaufer commented on _includes/schedule.js
> +    var url;
Why do you have `url` and `calId` namespaced outside of the for loop? Can't you change line 111 to `var calId = calendars[i]` and line 113 to `var url = ...`?

2018-03-02 04:58 UTC, mjkaufer commented on _includes/schedule.js
> +                // schedule.append("<tr" + oldClass + "><td>" + events[i].summary + "</td><td>" + startTime + "</td><td>" + endTime + "</td><td> " + location + "</td></tr>");
drop these bad boys from the codebase <3

2018-03-02 04:58 UTC, mjkaufer commented on _includes/schedule.js
> +                //return 1;
old commented code, pls remove

2018-03-02 04:58 UTC, mjkaufer commented on _includes/schedule.js
> +        } //END else
If you don't want to put this whole thing in an else statement, you can just `return false` on line 25 with `result.items.length == 0`, and then just run the rest of the code. I'll leave this up to you – either way, remove `//END else` pls

2018-03-02 05:28 UTC, mjkaufer submitted a review, later dismissed

2018-03-06 07:44 UTC, illegalprime submitted a review, later dismissed

2018-03-06 07:45 UTC, illegalprime commented
Looks good, please remove the merge commit by rebasing and then merge.

2018-03-06 15:37 UTC, mjkaufer commented
FYI I think you could've used `classList` without writing extra stuff https://caniuse.com/#search=classlist

Also, if you're gonna write fallback code that works on older platforms, feel free to just omit the original 'bleeding edge' code, since the old code will work on all platforms as it is.

2018-03-06 16:00 UTC, evan10s commented
Ah, ok.  That was from youmightnotneedjquery.com but I can fix that

On Mar 6, 2018 10:39 AM, "Matthew Kaufer" <notifications@github.com> wrote:

> FYI I think you could've used classList without writing extra stuff
> https://caniuse.com/#search=classlist
>
> Also, if you're gonna write fallback code that works on older platforms,
> feel free to just omit the original 'bleeding edge' code, since the old
> code will work on all platforms as it is.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HackGT/live-site/pull/14#issuecomment-370822286>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AFhZuVXJl2qxUiHZS4COldqjdgWrt_Dgks5tbq1VgaJpZM4SSd0b>
> .
>

2018-03-06 18:45 UTC, mjkaufer approved these changes

2018-03-06 18:47 UTC, merged