Rgoodling/footer
HackGT/live-site-old pull request #24
Opened 2018-03-05 03:30 UTC by rgoodling3

changed the footer

2018-03-05 04:26 UTC, evan10s requested changes
Off to a great start, but a few things could use some clean up

2018-03-05 04:26 UTC, evan10s commented on .idea/checkstyle-idea.xml
> +</project>
Can you add all the files in the `.idea` directory to the `.gitignore` file?  These are specific to your IDE, so you don't have to commit them to this repository.  After you modify the .gitignore file locally, commit it and then take a look at [this blog post](https://eric.blog/2014/05/11/remove-files-from-git-addingupdating-gitignore/) to remove the files you've ignored from the repository.

2018-03-05 04:26 UTC, evan10s commented on _includes/footer.html
> +          <p><a href = "https://docs.google.com/forms/d/e/1FAIpQLSdP3yiCMb4sSztn32tdwtDiZXud0vJNbUql-LD8au6noNTRqA/viewform?entry.1073143569=https://live.hack.gt/schedule&entry.267778992=Schedule&ent
1. This line is indented a little too much.
2. Instead of hard-coding the schedule page into the link, add a Jekyll variable for the current page title and the full page URL.  The [Jekyll site and page docs](https://jekyllrb.com/docs/variables/) will be helpful - to get the full path, you might have to combine the values of `site.url` and `page.url`.
3. That URL will change if people don't want to use the specific Google Form at that link.  However, you can fix this by adding an additional site parameter for the id of this feedback Google form.  The ID is the part of the URL between the `/`s after `/d/e` in the URL you use to fill out the form.

2018-03-05 04:26 UTC, evan10s commented on _includes/footer.html
> +      <div id="right" class="footer-col footer-col-3">
Another instance of using an `id` where there should be a class, but see my comment above about using Milligram classes here instead.

2018-03-05 04:26 UTC, evan10s commented on _includes/footer.html
> +<style>
Can you put this in a SASS file?  Also, you might not need this - see my other comments

2018-03-05 04:26 UTC, evan10s commented on _includes/social.html
>  <ul class="social-media-list">
Good job with the social media icons - they look good!

2018-03-05 04:26 UTC, evan10s commented on _includes/footer.html
> +          <li><a class="u-email" href="mailto:{{ site.email }}">{{ site.email }}</a></li>
This `<li>` tag doesn't appear to be between `<ul>` tags.

2018-03-05 04:26 UTC, evan10s commented on _includes/footer.html
>          <ul class="contact-list">
I think this needs to be moved up above the `if` block just above that contains an `<li>` tag.

2018-03-05 04:26 UTC, evan10s commented on _includes/footer.html
> +        </ul>
I think you've got an unmatched `</ul>` tag here; you can probably just remove this.

2018-03-05 04:26 UTC, evan10s commented on _config.yml
> +feedback: Give our site feedback!
I like that you've made this a variable; this way we can change the phrasing to fit the themes of individual events 👍

2018-03-05 04:26 UTC, evan10s commented on _includes/footer.html
> +    <div id="left" class="footer-col-wrapper">
`id="left"` should actually be a class, and not necessarily one that you create (IDs should never be used more than once; if that's the case, use a class).  Using responsive columns with the [Milligram CSS framework](https://milligram.io/#grids) we're already using in this project should mean that you can just use those classes rather than writing your own.

2018-03-06 17:40 UTC, evan10s commented on .gitignore
> +!/.idea/
Is this supposed to be just `.idea/`?

2018-03-06 17:43 UTC, rgoodling3 commented on .gitignore
> +!/.idea/
I don't know I didn't change that line.

2018-03-06 22:10 UTC, evan10s requested changes

2018-03-06 22:10 UTC, evan10s commented on _event_pages/map.md
> +url: https://live.hack.gt/map
You don't need this here.  If you define a "domain" or similar variable in _config that stores everything before the first / in the URL (e.g.,, domain: live.build.hack.gt), then you can construct the page's full URL using `site.domain + page.url`, no frontmatter variables required.

2018-03-06 22:10 UTC, evan10s commented on _includes/footer.html
> +        <p><font size = 1px>{{ site.description | escape }}</font></p>
The site description is reallllly tiny, and also the font size should be set using SASS.  Honestly, I'm not even sure the description is necessary in the footer, so consider removing it

![image](https://user-images.githubusercontent.com/5790137/37061237-cad033e8-2160-11e8-92bb-52a7c4564fbc.png)

2018-03-06 22:10 UTC, evan10s commented on _includes/head.html
> +<<<<<<< HEAD
Please remove the merge conflict in this file, and keep only HEAD's version

2018-03-06 22:10 UTC, evan10s commented on _includes/social.html
> +<style>
SASS pls (inline style tags are bad, but you could create a footer.scss file and import that in main.scss)

2018-03-06 22:10 UTC, evan10s commented on _config.yml
> +url: https://docs.google.com/forms/d/e/1FAIpQLSdP3yiCMb4sSztn32tdwtDiZXud0vJNbUql-LD8au6noNTRqA/viewform?entry.1073143569={{ page.url| cgi_escape | escape }}&entry.267778992={{ page.title| cgi_escape
The URL here turns into https://live-site-rgoodling-footer.pr.hack.gt/https%3A%2F%2Fdocs.google.com%2Fforms%2Fd%2Fe%2F1FAIpQLSdP3yiCMb4sSztn32tdwtDiZXud0vJNbUql-LD8au6noNTRqA%2Fviewform%3Fentry.1073143569%3D%7B%7B+page.url%7C+cgi_escape+%7C+escape+%7D%7D%26entry.267778992%3D%7B%7B+page.title%7C+cgi_escape+%7C+escape+%7D%7D%26entry.2080441427%26entry.1331555321%26entry.278526493

when you click it - basically, it's not leading to the right place

2018-03-07 22:54 UTC, kexin-zhang commented
Can we also include our Facebook link in the footer?

2018-03-08 05:37 UTC, evan10s approved these changes

2018-03-08 05:38 UTC, evan10s reviewed
I accidentally approved this... carry on nothing to see here 😬

2018-03-08 05:38 UTC, evan10s requested changes
I accidentally approved this... carry on nothing to see here 😬

2018-03-08 23:16 UTC, evan10s submitted a review, later dismissed
👍

2018-03-08 23:51 UTC, evan10s approved these changes
Should be good now

2018-03-08 23:54 UTC, merged